# Exercise 8: Check what type of number are the elements of an array.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, -1+3j, 3 ,2j])

a

array([ 1.+0.j,  2.+0.j,  3.+0.j, -1.+3.j,  3.+0.j,  0.+2.j])

In [3]:
np.iscomplex(a)

array([False, False, False,  True, False,  True])

In [4]:
np.isreal(a)

array([ True,  True,  True, False,  True, False])

In [5]:
b = 5.3232

np.isscalar(b)

True